echo " $(printf '%0.1s' "-"{1..50})";
echo -n " ";
echo -n "$(printf '%-10s' PID)";
echo -n "$(printf '%-10s' USER)";
echo -n "$(printf '%-15s' COMMAND)";
echo -n "$(printf '%-15s' MEMORY)";
echo;
echo " $(printf '%0.1s' "-"{1..50})";
for i in $(printf -- '%s\n' `ls /proc` | egrep "^[[:digit:]]+$");
	do if test -f "/proc/${i}/comm";
		then echo -n " ";
		echo -n "$(printf '%-10s' ${i})";
		echo -n "$(printf '%-10s' $(ls -l /proc/${i}/comm | cut -d ' ' -f 4))";
		echo -n "$(printf '%-15s' $(cat /proc/${i}/comm))";
		echo -n "$(printf '%-15s' "$(cat /proc/${i}/status | egrep "VmRSS" | cut -f 2-)")";
		echo;
	fi;
done;
echo " $(printf '%0.1s' "-"{1..50})";